language: python
python: "3.6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  matrix:
  - TENSORFLOW_VERSION=1.8
  - TENSORFLOW_VERSION=1.12
  - TENSORFLOW_VERSION=1.14
before_install:
  - pip install --upgrade pip
  - pip install tensorflow==$TENSORFLOW_VERSION
install:
  - pip install .[test]
script:
  - cd source/tests && python -m unittest
