language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - gcc-5
    - g++-5
    - gcc-6
    - g++-6
    - gcc-7
    - g++-7
    - gcc-8
    - g++-8
    - cmake
matrix:
  include:
    - python: 3.6
      env: 
      - CC=gcc-4.8
      - CXX=g++-4.8
      - TENSORFLOW_VERSION=1.8
    - python: 3.6
      env: 
      - CC=gcc-4.8
      - CXX=g++-4.8
      - TENSORFLOW_VERSION=1.12
    - python: 3.6
      env: 
      - CC=gcc-4.8
      - CXX=g++-4.8
      - TENSORFLOW_VERSION=1.14
    - python: 3.6
      env: 
      - CC=gcc-5
      - CXX=g++-5
      - TENSORFLOW_VERSION=1.14
    - python: 3.6
      env: 
      - CC=gcc-8
      - CXX=g++-8
      - TENSORFLOW_VERSION=1.14
    - python: 3.7
      env: 
      - CC=gcc-5
      - CXX=g++-5
      - TENSORFLOW_VERSION=1.14
    - python: 3.7
      env: 
      - CC=gcc-8
      - CXX=g++-8
      - TENSORFLOW_VERSION=1.14
before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install tensorflow==$TENSORFLOW_VERSION
install:
  - pip install --verbose .[test]
script:
  - cd source/tests && python -m unittest
